ansible_connection: "winrm"
ansible_winrm_server_cert_validation: ignore
# PROXY_EDSI=http://127.0.0.1:8118
ansible_winrm_proxy: "{{ lookup('env', 'PROXY_EDSI') }}"
ansible_winrm_operation_timeout_sec: 30
ansible_winrm_read_timeout_sec: 60
